#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
File: raijin_sync_to_sc
Author: Tom Mason
Email: tommason14@gmail.com
Github: https:github.com/tommason14
Description: rsync wrapper for raijin
"""

import os
import sys

if len(sys.argv) <= 3:
    print('Syntax: raijin_sync_to_sc EXT1 EXT2 ... LOCAL_PATH REMOTE_PATH')

else:
    args = sys.argv[1:]
    extensions = args[:-2]
    REMOTE_DIR = args[-1]
    LOCAL_DIR = args[-2]


    string = "rsync -rav -e ssh --include '*/' "

    for ext in extensions:
        string += f"--include '*.{ext}' "

    string += f"--exclude='*' {LOCAL_DIR} tm3124@raijin.nci.org.au:/short/k96/tm3124/{REMOTE_DIR}"

    os.system(string)
