#!/usr/bin/env zsh

# # Show system statistics
# fn + lalt - 1 : "${HOME}"/.config/yabai/scripts/show_cpu.sh
# fn + lalt - 2 : "${HOME}"/.config/yabai/scripts/show_mem.sh
# fn + lalt - 3 : "${HOME}"/.config/yabai/scripts/show_bat.sh
# fn + lalt - 4 : "${HOME}"/.config/yabai/scripts/show_disk.sh
# fn + lalt - 5 : "${HOME}"/.config/yabai/scripts/show_song.sh


# Navigation
alt - left : yabai -m window --focus west
alt - down : yabai -m window --focus south
alt - up : yabai -m window --focus north
alt - right : yabai -m window --focus east

# Moving windows
cmd + alt - left : yabai -m window --warp west
cmd + alt - down : yabai -m window --warp south
cmd + alt - up : yabai -m window --warp north
cmd + alt - right : yabai -m window --warp east

# Move focus container to workspace
shift + alt - m : yabai -m window --space last && yabai -m space --focus last
lctrl + cmd - left : yabai -m window --space prev && yabai -m space --focus prev
lctrl + cmd - right : yabai -m window --space next && yabai -m space --focus next

# Move to new desktop, but don't move the current focused window

# cmd - left : yabai -m space --focus prev
# cmd - right : yabai -m space --focus next

# shift + alt - 1 : yabai -m window --space 1 && yabai -m space --focus 1
# shift + alt - 2 : yabai -m window --space 2 && yabai -m space --focus 2
# shift + alt - 3 : yabai -m window --space 3 && yabai -m space --focus 3
# shift + alt - 4 : yabai -m window --space 4 && yabai -m space --focus 4
# shift + alt - 5 : yabai -m window --space 5 && yabai -m space --focus 5
# shift + alt - 6 : yabai -m window --space 6 && yabai -m space --focus 6

# move windows with ctrl-cmd number
# move to window with ctrl number
lctrl + cmd - 1 : yabai -m window --space 1
lctrl + cmd - 2 : yabai -m window --space 2
lctrl + cmd - 3 : yabai -m window --space 3
lctrl + cmd - 4 : yabai -m window --space 4
lctrl + cmd - 5 : yabai -m window --space 5

lctrl - 1 : yabai -m space --focus 1
lctrl - 2 : yabai -m space --focus 2
lctrl - 3 : yabai -m space --focus 3
lctrl - 4 : yabai -m space --focus 4
lctrl - 5 : yabai -m space --focus 5

# Resize windows
lctrl + alt - left : \
    yabai -m window --resize left:-20:0 ; \
    yabai -m window --resize right:-20:0

lctrl + alt - down : \
    yabai -m window --resize bottom:0:20 ; \
    yabai -m window --resize top:0:20

lctrl + alt - up : \
    yabai -m window --resize top:0:-20 ; \
    yabai -m window --resize bottom:0:-20

lctrl + alt - right : \
    yabai -m window --resize right:20:0 ; \
    yabai -m window --resize left:20:0

# cmd + alt + = (plus)
cmd + alt - 0x18 : \
    yabai -m window --resize top:0:-20 ; \
    yabai -m window --resize bottom:0:20 ; \
    yabai -m window --resize left:-20:0 ; \
    yabai -m window --resize right:20:0
        
# cmd + alt + -
cmd + alt - 0x1B : \
    yabai -m window --resize top:0:20 ; \
    yabai -m window --resize bottom:0:-20 ; \
    yabai -m window --resize left:20:0 ; \
    yabai -m window --resize right:-20:0

# Float and center window
cmd + alt - c : yabai -m window --toggle float;\
                  yabai -m window --grid 4:4:1:1:2:2

# Equalize size of windows
cmd + alt - 0 : yabai -m space --balance

# Enable / Disable gaps in current workspace
lctrl + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# Rotate windows clockwise and anticlockwise
alt - r         : yabai -m space --rotate 90
shift + alt - r : yabai -m space --rotate 270

# Rotate on X and Y Axis
shift + alt - x : yabai -m space --mirror x-axis
shift + alt - y : yabai -m space --mirror y-axis

# Set insertion point for focused container
shift + lctrl + alt - h : yabai -m window --insert west
shift + lctrl + alt - j : yabai -m window --insert south
shift + lctrl + alt - k : yabai -m window --insert north
shift + lctrl + alt - l : yabai -m window --insert east

# Float / Unfloat window 

toggle_float(){
 if [[ $(yabai -m query --spaces --space | jq -r '.type') == bsp ]]
 then
   yabai -m space --layout "float" && yabai -m config focus_follows_mouse off
 else
  yabai -m space --layout "bsp" && yabai -m config focus_follows_mouse autoraise
 fi
}

shift + alt - space : toggle_float
 

# Restart Yabai
lctrl + alt - r : 
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Make window native fullscreen
alt - f         : yabai -m window --toggle zoom-fullscreen
cmd + alt - f : yabai -m window --toggle native-fullscreen

# open apps
cmd + alt - r : open /Applications/RStudio.app/
# try and get this working...
cmd + alt - y : vim ~/dotfiles/yabairc
