#!/usr/bin/env sh

source ~/.cache/wal/colors.sh # pywal scheme

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

yabai -m config status_bar                   on
yabai -m config status_bar_background_color  0xff$CBACK
yabai -m config status_bar_foreground_color  0xff$CFORE

yabai -m config active_window_border_color   0xff$CACTV
yabai -m config normal_window_border_color   0xff$CNORM
yabai -m config insert_window_border_color   0xff$CINSE

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0xaa00c4fe
# yabai -m config normal_window_border_color   0xaa808080
# yabai -m config insert_window_border_color   0xffffffff
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               30
yabai -m config left_padding                 30
yabai -m config right_padding                30
yabai -m config window_gap                   10

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

yabai -m signal --add event=space_changed action="bash ~/dotfiles/yabai_scripts/autodestroy.sh"

# # refresh primary display workspaces
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"
#
# # refresh secondary display workspaces
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-secondary-jsx\"'"
