#!/usr/bin/env sh

source ~/.cache/wal/colors.sh # pywal scheme

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

yabai -m config active_window_border_color   0xff$CACTV
yabai -m config normal_window_border_color   0xff$CNORM
yabai -m config insert_window_border_color   0xff$CINSE

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_radius         8
yabai -m config window_border_width          1
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# on work comp, make floating the default
[[ $USER == "tmas0023" ]] && yabai -m config layout float || yabai -m config layout bsp

yabai -m config top_padding                  30
yabai -m config bottom_padding               30
yabai -m config left_padding                 30
yabai -m config right_padding                30
yabai -m config window_gap                   10


yabai -m signal --add event=space_changed action="bash ~/dotfiles/yabai_scripts/autodestroy.sh"

# # refresh primary display workspaces
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"
#
# # refresh secondary display workspaces
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-secondary-jsx\"'"

# disable for preference panes
yabai -m rule --add title='Preferences$' manage=off topmost=on

# 'Desktop 2' floating windows
# yabai -m config --space 2 layout float && yabai -m config --space 2 focus_follows_mouse autoraise
#
