
# Files {{{2

alias oba='vim ~/dotfiles/bash_aliases && source ~/.bashrc'
alias obf='vim ~/dotfiles/bash_functions && source ~/.bashrc'
alias obp='vim ~/.bash_profile && source ~/.bashrc'
alias obr='vim ~/.bashrc && source ~/.bashrc'
alias oip='vim ~/dotfiles/jupyter/ipythonrc'
alias orp='vim ~/dotfiles/Rprofile'
alias ov='vim ~/dotfiles/vimrc'

# Movement {{{2

alias gbk='cd /Volumes/GoogleDrive/My\ Drive/backups'
alias gca='cd /Volumes/GoogleDrive/My\ Drive/hydrated_ILs/Analysis'
alias gdc='cd ~/Documents'
alias gdf='cd ~/dotfiles'
alias gdk='cd ~/Desktop'
alias gdp='cd ~/Documents/repos/dopamine/dopamine_paper'
alias gdw='cd ~/Downloads'
alias gfd='cd /Volumes/GoogleDrive/My\ Drive/Dopamine'
alias gfo='cd /Volumes/GoogleDrive/My\ Drive'
alias gfp='cd /Volumes/GoogleDrive/My\ Drive/polymers'
alias gmc='cd ~/Documents/repos/mccg'
alias gmo='cd ~/Movies'
alias gpc='cd ~/Pictures'
alias gq='cd ~/Documents/repos/qcp'
alias grp='cd ~/Documents/repos'
alias gsc='cd /Volumes/GoogleDrive/My\ Drive/scripts'
alias gth='cd ~/Documents/repos/thesis'
